### ISSUE TITLE
Suggest to include build task in deploy task, and use dist files in index.html of gh-pages branch

### ISSUE THREAD

**Issue by liuwenchao** [webcomponents/polymer-boilerplate#17]
I'm keeping forgot to build before running deploy, and it's worse when I made a release w/o knowing the dist files are not updated.

**Comment by zenorocha** [comment]
The [new release](https://github.com/webcomponents/polymer-boilerplate/releases/tag/v1.1.0) leverages polyserve which should mitigate this problem.

**Comment by liuwenchao** [comment]
Does that mean we lose feature: 'check it live'?

**Comment by zenorocha** [comment]
@liuwenchao it doesn't. You'll still be able to see it live in `gh-pages` branch but you'll need a different code base for that which consists in a `bower.json` file to grab dependencies and a `index.html` that redirects to the demo.

Check: https://github.com/webcomponents/hello-world-polymer/tree/gh-pages

It's less automated indeed but at least we don't introduce any additional tool.

Do you think we should have should branch here as well?

**Comment by liuwenchao** [comment]
I think we should at least point out how to do this in README, maybe make it a separate repository.
