### ISSUE TITLE
Any plan to upgrade to polymer 0.8?

### ISSUE THREAD

**Issue by liuwenchao** [webcomponents/polymer-boilerplate#24]
I'm trying to upgrade my elements to polymer 0.8, I can put up a PR for this boilerplate after upgrading. Just checking if this is in need, or I shouldn't do it.

**Comment by zenorocha** [comment]
Would be awesome if you can send a PR @liuwenchao ;)

**Comment by obetomuniz** [comment]
Amazing @liuwenchao ... Can you do it?

**Comment by zenorocha** [comment]
Done!
